### ISSUE TITLE
Create Data Ingestion Service

### ISSUE THREAD

**Issue by lastlegion** [sharmalab/VizRec#23]
*Acceptance criteria*

- Data is POSTed to `/ingest` endpoint
- Data is stored in Mongo

*Technical notes*

- Use mongodb
- Use PyMongo

**Comment by SapoonDutta** [comment]
Acceptance criteria

- Data is stored and is accessible for different functions as necessary for the program.


Technical notes

- Use mongodb
- Use PyMongo
