### ISSUE TITLE
Create Filtering Service

### ISSUE THREAD

**Issue by lastlegion** [sharmalab/VizRec#24]
Acceptance Criteria :

Create the analytical backend to run queries for filtering.
Includes fast queries that post on the database.
Returns result in the valid format that can be used by the VizRec system.
Technical Notes :

use cube.dev
use mongodb as the underlying database.

**Comment by SapoonDutta** [comment]
Acceptance Criteria : 
- Create the analytical backend to run queries for filtering.
- Includes fast queries that post on the database.
- Returns result in the valid format that can be used by the VizRec system.

Technical Notes :
- use cube.dev
- use mongodb as the underlying database.
