### ISSUE TITLE
Setup Model registry

### ISSUE THREAD

**Issue by lastlegion** [sharmalab/VizRec#29]

**Comment by PVinay737** [comment]
Acceptance criteria

 - Set Up a private registry for building and storing the models

Technical Notes
     
 - Use Docker

**Comment by SapoonDutta** [comment]
Acceptance Criteria :

- Have the start point and endpoint of the registry set up.
- Proper documentation of how to insert different models into the registry and expected input and output from the model code. 

Technical Notes : 
- Docker for containerizing the registry
- Python for creating the required framework to insert and delete models.
