### ISSUE TITLE
Auto generate filtering service schema

### ISSUE THREAD

**Issue by lastlegion** [sharmalab/VizRec#44]

**Comment by PVinay737** [comment]
Acceptance criteria

 - Ingestion service should generate dimensions,measures and filters for the schema file of filtering service

Technical Notes
     
 - Use Python

**Comment by ghostaccount737** [comment]
Acceptance criteria

 - Ingestion service should generate dimensions, measures, and filters for the schema file of filtering service

Technical Notes
     
 - Use Python
